# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaLoginRealizado.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Login_Realizado(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 548)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fundo = QtWidgets.QFrame(self.centralwidget)
        self.fundo.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.fundo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fundo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo.setObjectName("fundo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fundo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.fundo)
        self.frame_2.setMaximumSize(QtCore.QSize(300, 500))
        self.frame_2.setStyleSheet("background-color:rgb(175, 232, 189);\n"
"border-radius: 30px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Botao_Sair = QtWidgets.QPushButton(self.frame_2)
        self.Botao_Sair.setGeometry(QtCore.QRect(214, 452, 71, 21))
        self.Botao_Sair.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(110, 110, 110);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(200, 255, 200);\n"
"    color: rgb(10, 10, 10);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(150, 255, 150);\n"
"    color: rgb(10, 10, 10);\n"
"}")
        self.Botao_Sair.setObjectName("Botao_Sair")
        self.logo = QtWidgets.QFrame(self.frame_2)
        self.logo.setGeometry(QtCore.QRect(110, 80, 71, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setStyleSheet("background-image: url(:/logomini/natec logo mini.png);\n"
"background-repeat: no repeat;\n"
"background-position: center;")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.text_BemVindo = QtWidgets.QTextBrowser(self.frame_2)
        self.text_BemVindo.setGeometry(QtCore.QRect(100, 160, 111, 31))
        self.text_BemVindo.setObjectName("text_BemVindo")
        self.pato = QtWidgets.QFrame(self.frame_2)
        self.pato.setGeometry(QtCore.QRect(-20, 190, 321, 231))
        self.pato.setStyleSheet("background-image: url(:/pato/patogirando.gif);")
        self.pato.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pato.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pato.setObjectName("pato")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.fundo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        # self..Botao_Sair.clicked.connect(QtWidgets.qApp.quit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Botao_Sair.setText(_translate("MainWindow", "Sair"))
        self.text_BemVindo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Bem Vindo</span></p></body></html>"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Login_Realizado()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
