# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 548)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fundo = QtWidgets.QFrame(self.centralwidget)
        self.fundo.setStyleSheet("background-color: rgb(207, 207, 207);")
        self.fundo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fundo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fundo.setObjectName("fundo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fundo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.fundo)
        self.frame_2.setMaximumSize(QtCore.QSize(300, 500))
        self.frame_2.setStyleSheet("background-color:rgb(175, 232, 189);\n"
"border-radius: 30px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.caixa_usuario = QtWidgets.QLineEdit(self.frame_2)
        self.caixa_usuario.setGeometry(QtCore.QRect(90, 190, 131, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caixa_usuario.sizePolicy().hasHeightForWidth())
        self.caixa_usuario.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.caixa_usuario.setFont(font)
        self.caixa_usuario.setToolTipDuration(-1)
        self.caixa_usuario.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(110, 110, 110);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color: rgb(200, 255, 200);\n"
"    color: rgb(10, 10, 10);\n"
"}")
        self.caixa_usuario.setText("")
        self.caixa_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.caixa_usuario.setDragEnabled(False)
        self.caixa_usuario.setClearButtonEnabled(False)
        self.caixa_usuario.setObjectName("caixa_usuario")
        self.caixa_senha = QtWidgets.QLineEdit(self.frame_2)
        self.caixa_senha.setGeometry(QtCore.QRect(90, 250, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.caixa_senha.setFont(font)
        self.caixa_senha.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(110, 110, 110);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QLineEdit:focus{\n"
"    background-color: rgb(200, 255, 200);\n"
"    color: rgb(10, 10, 10);\n"
"}")
        self.caixa_senha.setText("")
        self.caixa_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.caixa_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.caixa_senha.setDragEnabled(False)
        self.caixa_senha.setClearButtonEnabled(False)
        self.caixa_senha.setObjectName("caixa_senha")
        self.Botao_Voltar = QtWidgets.QPushButton(self.frame_2)
        self.Botao_Voltar.setGeometry(QtCore.QRect(214, 452, 71, 21))
        self.Botao_Voltar.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(110, 110, 110);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(200, 255, 200);\n"
"    color: rgb(10, 10, 10);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(150, 255, 150);\n"
"    color: rgb(10, 10, 10);\n"
"}")
        self.Botao_Voltar.setObjectName("Botao_Voltar")
        self.Botao_Entrar = QtWidgets.QPushButton(self.frame_2)
        self.Botao_Entrar.setGeometry(QtCore.QRect(150, 310, 71, 21))
        self.Botao_Entrar.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(150,150,150);\n"
"    border-radius: 5px;\n"
"    padding: 15px;\n"
"    background-color: rgb(110, 110, 110);\n"
"    color: rgb(200, 200, 200);\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(200, 255, 200);\n"
"    color: rgb(10, 10, 10);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(150, 255, 150);\n"
"    color: rgb(10, 10, 10);\n"
"}")
        self.Botao_Entrar.setObjectName("Botao_Entrar")
        self.logo = QtWidgets.QFrame(self.frame_2)
        self.logo.setGeometry(QtCore.QRect(10, 0, 71, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setStyleSheet("background-image: url(:/logomini/natec logo mini.png);\n"
"background-repeat: no repeat;\n"
"background-position: center;")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser.setGeometry(QtCore.QRect(120, 150, 81, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.fundo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.caixa_usuario.setPlaceholderText(_translate("MainWindow", "Usuário"))
        self.caixa_senha.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.Botao_Voltar.setText(_translate("MainWindow", "Voltar"))
        self.Botao_Entrar.setText(_translate("MainWindow", "Entrar"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Login</span></p></body></html>"))
import logo_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
